// 4P3X Internal Built-in AI Agent Registry — RUN 1 + RUN 2 + RUN 3
// All agents are advisory, limited-authority, and non-autonomous.
// Autonomy, file editing, and external API calls are permanently forbidden in Run 3.

const agentRegistry = [

  // ─── Run 1 / Run 3 Active ────────────────────────────────────────────────
  {
    id: 'apiConfigAgent',
    name: 'API Config Agent',
    description: 'Reviews AI/API provider configuration status, missing fields, key safety, local-only warnings, and provider readiness. Operates on masked config data only.',
    status: 'active',
    category: 'configuration',
    purpose: 'Review AI/API provider configuration status, missing fields, key safety, local-only warnings, and provider readiness.',
    allowedActions: [
      'read_ai_config_status',
      'validate_provider_config',
      'display_warnings',
      'write_recommendation',
    ],
    forbiddenActions: [
      'call_external_api',
      'store_raw_keys',
      'log_secrets',
      'auto_configure',
      'edit_files',
      'expose_raw_keys',
    ],
    inputTypes: ['provider_id', 'config_shape', 'masked_key_status'],
    outputTypes: ['status_message', 'warning_list', 'validation_result', 'recommendation'],
    requiresExternalAI: false,
    supportedProviders: ['none'],
    runToBuild: 1,
    safetyLevel: 'low-risk',
    autonomyAllowed: false,
    fileEditAllowed: false,
    externalApiCallsAllowed: false,
    destructiveActionsAllowed: false,
    requiresUserApprovalForActions: true,
    canReadBlueprints: false,
    canReadTransformationReadiness: false,
    canReadApiConfigStatus: true,
    canWriteRecommendations: true,
    canModifyState: false,
    canExportReports: false,
    visibleInRun2: true,
    visibleInRun3: true,
    panelType: 'active_status',
  },

  // ─── Run 3 Active ────────────────────────────────────────────────────────
  {
    id: 'systemArchitectAgent',
    name: 'System Architect Agent',
    description: 'Analyses active blueprint architecture, module dependencies, state mode, SSOT alignment, and transformation risks.',
    status: 'active',
    category: 'architecture',
    purpose: 'Analyse active blueprint architecture, module dependencies, state mode, SSOT alignment, and transformation risks.',
    allowedActions: [
      'read_blueprint',
      'read_module_registry',
      'read_transformation_readiness',
      'write_recommendation',
      'identify_architecture_risks',
      'recommend_run_sequencing',
    ],
    forbiddenActions: [
      'edit_files',
      'rewrite_code',
      'direct_refactor_execution',
      'create_backend',
      'call_external_api',
      'modify_blueprint_directly',
    ],
    inputTypes: ['active_blueprint', 'module_registry', 'readiness_score'],
    outputTypes: ['architecture_review', 'dependency_warnings', 'ssot_confirmation', 'run_sequencing_advice', 'recommendation'],
    requiresExternalAI: false,
    supportedProviders: ['openai', 'anthropic', 'google', 'groq', 'openrouter', 'ollama'],
    runToBuild: 3,
    safetyLevel: 'medium-risk',
    autonomyAllowed: false,
    fileEditAllowed: false,
    externalApiCallsAllowed: false,
    destructiveActionsAllowed: false,
    requiresUserApprovalForActions: true,
    canReadBlueprints: true,
    canReadTransformationReadiness: true,
    canReadApiConfigStatus: false,
    canWriteRecommendations: true,
    canModifyState: false,
    canExportReports: false,
    visibleInRun3: true,
    panelType: 'advisory_analysis',
  },
  {
    id: 'uxLogicAgent',
    name: 'UX Logic Agent',
    description: 'Analyses user flows, page structure, empty/loading/error/success states, navigation, accessibility basics, and mobile logic.',
    status: 'active',
    category: 'ux',
    purpose: 'Analyse user flows, page structure, screen states, navigation logic, accessibility basics, and mobile responsiveness.',
    allowedActions: [
      'read_blueprint',
      'read_user_flows',
      'read_module_registry',
      'write_recommendation',
      'identify_missing_screen_states',
      'suggest_navigation_improvements',
    ],
    forbiddenActions: [
      'redesign_entire_ui',
      'replace_existing_layout',
      'create_unrelated_components',
      'edit_files',
      'call_external_api',
    ],
    inputTypes: ['active_blueprint', 'user_flows', 'ui_layout_profile'],
    outputTypes: ['ux_flow_review', 'missing_screen_states', 'navigation_warnings', 'accessibility_reminders', 'recommendation'],
    requiresExternalAI: false,
    supportedProviders: ['openai', 'anthropic', 'google', 'groq', 'openrouter', 'ollama'],
    runToBuild: 3,
    safetyLevel: 'low-risk',
    autonomyAllowed: false,
    fileEditAllowed: false,
    externalApiCallsAllowed: false,
    destructiveActionsAllowed: false,
    requiresUserApprovalForActions: true,
    canReadBlueprints: true,
    canReadTransformationReadiness: false,
    canReadApiConfigStatus: false,
    canWriteRecommendations: true,
    canModifyState: false,
    canExportReports: false,
    visibleInRun3: true,
    panelType: 'advisory_analysis',
  },
  {
    id: 'validationAgent',
    name: 'Validation Agent',
    description: 'Reviews blueprint completeness, readiness score, validation gates, acceptance criteria, and blocked requirements.',
    status: 'active',
    category: 'validation',
    purpose: 'Review blueprint completeness, readiness score, validation gates, and identify blockers and missing requirements.',
    allowedActions: [
      'read_blueprint',
      'read_readiness_score',
      'read_transformation_rules',
      'write_recommendation',
      'identify_missing_requirements',
      'identify_blockers',
    ],
    forbiddenActions: [
      'claim_validation_passed_without_checks',
      'skip_missing_requirements',
      'modify_state_outside_recommendation_queue',
      'edit_files',
      'call_external_api',
    ],
    inputTypes: ['active_blueprint', 'readiness_score', 'transformation_rules'],
    outputTypes: ['validation_checklist', 'missing_requirements', 'risk_score', 'blocker_list', 'recommendation'],
    requiresExternalAI: false,
    supportedProviders: ['openai', 'anthropic', 'google', 'groq', 'openrouter', 'ollama'],
    runToBuild: 3,
    safetyLevel: 'low-risk',
    autonomyAllowed: false,
    fileEditAllowed: false,
    externalApiCallsAllowed: false,
    destructiveActionsAllowed: false,
    requiresUserApprovalForActions: true,
    canReadBlueprints: true,
    canReadTransformationReadiness: true,
    canReadApiConfigStatus: false,
    canWriteRecommendations: true,
    canModifyState: false,
    canExportReports: false,
    visibleInRun3: true,
    panelType: 'advisory_analysis',
  },
  {
    id: 'refactorPlannerAgent',
    name: 'Refactor Planner Agent',
    description: 'Recommends safe future transformation steps and run sequencing without performing any transformation.',
    status: 'active',
    category: 'planning',
    purpose: 'Recommend safe transformation paths, next run sequencing, do-not-touch boundaries, and rollback planning.',
    allowedActions: [
      'read_blueprint',
      'read_transformation_readiness',
      'read_module_registry',
      'write_recommendation',
      'suggest_run_sequencing',
      'identify_do_not_touch_boundaries',
    ],
    forbiddenActions: [
      'perform_refactor',
      'rewrite_storage_js',
      'delete_files',
      'build_variants_early',
      'edit_files',
      'call_external_api',
    ],
    inputTypes: ['active_blueprint', 'readiness_score', 'module_registry', 'transformation_state'],
    outputTypes: ['transformation_path', 'next_run_recommendation', 'do_not_touch_list', 'rollback_notes', 'recommendation'],
    requiresExternalAI: false,
    supportedProviders: ['openai', 'anthropic', 'google', 'groq', 'openrouter', 'ollama'],
    runToBuild: 3,
    safetyLevel: 'medium-risk',
    autonomyAllowed: false,
    fileEditAllowed: false,
    externalApiCallsAllowed: false,
    destructiveActionsAllowed: false,
    requiresUserApprovalForActions: true,
    canReadBlueprints: true,
    canReadTransformationReadiness: true,
    canReadApiConfigStatus: false,
    canWriteRecommendations: true,
    canModifyState: false,
    canExportReports: false,
    visibleInRun2: true,
    visibleInRun3: true,
    panelType: 'advisory_analysis',
    previewDescription: 'Advisory transformation planning. Recommends safe next steps only. Never performs transformation.',
    allowedFuturePurpose: 'Structured transformation planning assistant. Advisory only. Never autonomous.',
  },
  {
    id: 'safetyComplianceAgent',
    name: 'Safety Compliance Agent',
    description: 'Reviews product blueprint safety and compliance requirements for fleet, cybersecurity, HR/induction, and sensitive product types.',
    status: 'active',
    category: 'compliance',
    purpose: 'Identify safety and legal compliance risks in the blueprint. Raises flags for safety-critical, compliance-critical, and sensitive products.',
    allowedActions: [
      'read_blueprint',
      'read_safety_level',
      'read_product_type',
      'write_recommendation',
      'raise_safety_flags',
      'suggest_compliance_review',
    ],
    forbiddenActions: [
      'give_unsafe_cyber_instructions',
      'guarantee_legal_certainty',
      'encourage_proprietary_cloning',
      'edit_files',
      'call_external_api',
      'auto_approve_safety',
    ],
    inputTypes: ['active_blueprint', 'safety_level', 'product_type'],
    outputTypes: ['safety_warnings', 'compliance_flags', 'human_override_reminders', 'defensive_only_reminders', 'recommendation'],
    requiresExternalAI: false,
    supportedProviders: ['openai', 'anthropic', 'google'],
    runToBuild: 3,
    safetyLevel: 'high-risk',
    autonomyAllowed: false,
    fileEditAllowed: false,
    externalApiCallsAllowed: false,
    destructiveActionsAllowed: false,
    requiresUserApprovalForActions: true,
    canReadBlueprints: true,
    canReadTransformationReadiness: false,
    canReadApiConfigStatus: false,
    canWriteRecommendations: true,
    canModifyState: false,
    canExportReports: false,
    visibleInRun3: true,
    panelType: 'advisory_analysis',
  },
  {
    id: 'productStrategyAgent',
    name: 'Product Strategy Agent',
    description: 'Reviews product positioning, audience clarity, transformation value, packaging readiness, and portfolio/client usefulness.',
    status: 'active',
    category: 'strategy',
    purpose: 'Review product positioning, audience definition, and transformation readiness from a product strategy perspective.',
    allowedActions: [
      'read_blueprint',
      'read_identity',
      'read_readiness_score',
      'write_recommendation',
      'suggest_positioning',
      'identify_audience_gaps',
    ],
    forbiddenActions: [
      'change_core_identity_without_permission',
      'rebrand_without_approval',
      'add_unplanned_features',
      'present_unbuilt_features_as_complete',
      'edit_files',
      'call_external_api',
      'auto_publish',
    ],
    inputTypes: ['active_blueprint', 'identity', 'target_users', 'readiness_score'],
    outputTypes: ['product_clarity_review', 'positioning_suggestions', 'audience_gap_notes', 'packaging_advice', 'recommendation'],
    requiresExternalAI: false,
    supportedProviders: ['openai', 'anthropic', 'google', 'groq', 'openrouter'],
    runToBuild: 3,
    safetyLevel: 'low-risk',
    autonomyAllowed: false,
    fileEditAllowed: false,
    externalApiCallsAllowed: false,
    destructiveActionsAllowed: false,
    requiresUserApprovalForActions: true,
    canReadBlueprints: true,
    canReadTransformationReadiness: true,
    canReadApiConfigStatus: false,
    canWriteRecommendations: true,
    canModifyState: false,
    canExportReports: false,
    visibleInRun3: true,
    panelType: 'advisory_analysis',
  },
];

export function getActiveAgents()      { return agentRegistry.filter((a) => a.status === 'active'); }
export function getReservedAgents()    { return agentRegistry.filter((a) => a.status === 'reserved'); }
export function getAgentById(id)       { return agentRegistry.find((a) => a.id === id) || null; }
export function getRun2VisibleAgents() { return agentRegistry.filter((a) => a.visibleInRun2); }
export function getRun3VisibleAgents() { return agentRegistry.filter((a) => a.visibleInRun3); }
export function getAdvisoryAgents()    { return agentRegistry.filter((a) => a.status === 'active' && a.autonomyAllowed === false); }

export default agentRegistry;
