// 4P3X Agent Recommendations Page — RUN 3

import React, { useState, useEffect } from 'react';
import {
  getState, subscribe,
  acceptAgentRecommendation, dismissAgentRecommendation, convertRecommendationToFutureRun,
  clearAgentRecommendations,
} from '../state/storage.js';
import { getAgentById } from '../config/agentRegistry.js';
import AgentRecommendationQueue from '../components/agents/AgentRecommendationQueue.jsx';
import Badge from '../components/ui/Badge.jsx';
import Card from '../components/ui/Card.jsx';
import {
  sortRecommendationsByPriority, filterRecommendationsByAgent, filterRecommendationsByCategory,
  filterRecommendationsByStatus, getRecommendationCounts,
} from '../utils/agentOutput.js';

const AGENT_IDS  = ['systemArchitectAgent','uxLogicAgent','validationAgent','refactorPlannerAgent','apiConfigAgent','safetyComplianceAgent','productStrategyAgent'];
const CATEGORIES = ['architecture','ux','validation','refactor','api','safety','strategy'];
const STATUSES   = ['open','accepted','dismissed','converted_to_future_run'];
const PRIORITIES = ['critical','high','medium','low'];

export function AgentRecommendations({ onNavigate }) {
  const [state, setState]                 = useState(() => getState());
  const [filterAgent, setFilterAgent]     = useState('all');
  const [filterCat, setFilterCat]         = useState('all');
  const [filterStatus, setFilterStatus]   = useState('open');
  const [filterPriority, setFilterPriority] = useState('all');
  const [showClearConfirm, setShowClearConfirm] = useState(false);

  useEffect(() => {
    const unsub = subscribe((s) => setState({ ...s }));
    return unsub;
  }, []);

  const agentSystem = state.agentSystem || {};
  const allRecs     = agentSystem.recommendationQueue || [];
  const counts      = getRecommendationCounts(allRecs);

  let filtered = sortRecommendationsByPriority(allRecs);
  if (filterAgent !== 'all')    filtered = filterRecommendationsByAgent(filtered, filterAgent);
  if (filterCat !== 'all')      filtered = filterRecommendationsByCategory(filtered, filterCat);
  if (filterStatus !== 'all')   filtered = filterRecommendationsByStatus(filtered, filterStatus);
  if (filterPriority !== 'all') filtered = filtered.filter((r) => r.priority === filterPriority);

  function handleClearAll() {
    if (!showClearConfirm) { setShowClearConfirm(true); return; }
    clearAgentRecommendations();
    setShowClearConfirm(false);
  }

  return (
    <div>
      <div className="page-header">
        <div className="page-title">Agent Recommendations</div>
        <div className="page-subtitle">Advisory recommendations generated by local analysis agents</div>
      </div>

      <div className="grid-3" style={{ marginBottom: 20 }}>
        <Card>
          <div style={{ fontSize: 11, color: 'var(--text-muted)', marginBottom: 4 }}>TOTAL</div>
          <div style={{ fontSize: 28, fontWeight: 700, color: 'var(--gold-bright)' }}>{counts.total}</div>
          <div style={{ fontSize: 11, color: 'var(--text-muted)' }}>{counts.open} open · {counts.accepted} accepted</div>
        </Card>
        <Card>
          <div style={{ fontSize: 11, color: 'var(--text-muted)', marginBottom: 4 }}>CRITICAL / HIGH</div>
          <div style={{ fontSize: 28, fontWeight: 700, color: counts.critical > 0 ? '#ff6677' : 'var(--text-muted)' }}>
            {counts.critical + counts.high}
          </div>
          <div style={{ fontSize: 11, color: 'var(--text-muted)' }}>{counts.critical} critical · {counts.high} high</div>
        </Card>
        <Card>
          <div style={{ fontSize: 11, color: 'var(--text-muted)', marginBottom: 4 }}>DISMISSED</div>
          <div style={{ fontSize: 28, fontWeight: 700, color: 'var(--text-secondary)' }}>{counts.dismissed}</div>
          <div style={{ fontSize: 11, color: 'var(--text-muted)' }}>Filtered from open queue</div>
        </Card>
      </div>

      <div className="alert alert-info" style={{ marginBottom: 20 }}>
        Recommendations are generated by advisory agents from local state inspection only.
        They do not modify blueprints directly, call external APIs, or perform any automated action.
        Accept, dismiss, or convert each recommendation to a future run note.
      </div>

      <Card style={{ marginBottom: 20 }}>
        <div style={{ display: 'flex', gap: 10, flexWrap: 'wrap', alignItems: 'flex-end' }}>
          <div style={{ flex: 1, minWidth: 150 }}>
            <label className="form-label">Agent</label>
            <select className="form-input" value={filterAgent} onChange={(e) => setFilterAgent(e.target.value)}>
              <option value="all">All agents</option>
              {AGENT_IDS.map((id) => <option key={id} value={id}>{getAgentById(id)?.name || id}</option>)}
            </select>
          </div>
          <div style={{ flex: 1, minWidth: 130 }}>
            <label className="form-label">Category</label>
            <select className="form-input" value={filterCat} onChange={(e) => setFilterCat(e.target.value)}>
              <option value="all">All categories</option>
              {CATEGORIES.map((c) => <option key={c} value={c}>{c}</option>)}
            </select>
          </div>
          <div style={{ flex: 1, minWidth: 120 }}>
            <label className="form-label">Status</label>
            <select className="form-input" value={filterStatus} onChange={(e) => setFilterStatus(e.target.value)}>
              <option value="all">All statuses</option>
              {STATUSES.map((s) => <option key={s} value={s}>{s.replace(/_/g,' ')}</option>)}
            </select>
          </div>
          <div style={{ flex: 1, minWidth: 110 }}>
            <label className="form-label">Priority</label>
            <select className="form-input" value={filterPriority} onChange={(e) => setFilterPriority(e.target.value)}>
              <option value="all">All priorities</option>
              {PRIORITIES.map((p) => <option key={p} value={p}>{p}</option>)}
            </select>
          </div>
          {allRecs.length > 0 && (
            <div style={{ paddingBottom: 4 }}>
              <button className="btn btn-danger btn-sm" onClick={handleClearAll}>Clear All</button>
            </div>
          )}
        </div>
        {showClearConfirm && (
          <div className="alert alert-warn" style={{ marginTop: 12 }}>
            <div style={{ fontSize: 12, marginBottom: 8 }}>Confirm: permanently clear all {allRecs.length} recommendations?</div>
            <div style={{ display: 'flex', gap: 8 }}>
              <button className="btn btn-danger btn-sm" onClick={handleClearAll}>Yes, Clear All</button>
              <button className="btn btn-ghost btn-sm" onClick={() => setShowClearConfirm(false)}>Cancel</button>
            </div>
          </div>
        )}
        <div style={{ marginTop: 10, fontSize: 11, color: 'var(--text-muted)' }}>
          Showing {filtered.length} of {allRecs.length} recommendations
        </div>
      </Card>

      <AgentRecommendationQueue
        recommendations={filtered}
        onAccept={acceptAgentRecommendation}
        onDismiss={dismissAgentRecommendation}
        onConvertToFutureRun={convertRecommendationToFutureRun}
      />

      {allRecs.length === 0 && (
        <div style={{ textAlign: 'center', marginTop: 24 }}>
          <button className="btn btn-primary" onClick={() => onNavigate('/agent-workbench')}>
            Go to Agent Workbench to run agents →
          </button>
        </div>
      )}

      {allRecs.length > 0 && (
        <div style={{ marginTop: 20, background: '#0a1a0a', border: '1px solid #166534', borderRadius: 8, padding: 16 }}>
          <div style={{ fontSize: 13, fontWeight: 700, color: '#22c55e', marginBottom: 6 }}>
            ✅ Recommendations reviewed? Ready to compile.
          </div>
          <div style={{ fontSize: 12, color: '#9ca3af', marginBottom: 12 }}>
            Agent recommendations have been incorporated. Proceed to the Transformation Compiler to generate a product skeleton plan.
          </div>
          <div style={{ display: 'flex', gap: 10, flexWrap: 'wrap' }}>
            <button className="btn btn-primary" onClick={() => onNavigate('/transformation-compiler')}>
              Open Transformation Compiler →
            </button>
            <button className="btn btn-ghost btn-sm" onClick={() => onNavigate('/agent-workbench')}>
              Run more agents →
            </button>
          </div>
        </div>
      )}
    </div>
  );
}

export default AgentRecommendations;
