// 4P3X Blueprint Presets — RUN 2
// Production-grade blueprint starter configurations.
// These are transformation-ready starting points — production starter configurations only.
// No product features are built here. Used to initialise blueprint objects.

const blueprintPresets = [
  {
    id: 'baseReusableFoundation',
    name: 'Reusable Base Foundation',
    productType: 'foundation',
    description: 'The core production foundation. All product variants are transformed from this blueprint.',
    defaultCoreModules: ['dashboard', 'modules', 'variantProfile', 'aiConfig', 'settings'],
    defaultOptionalModules: [],
    defaultDataEntities: ['AppConfig', 'UserPreferences', 'SystemHealth'],
    defaultUserFlows: [
      'User opens dashboard and reviews system health',
      'User selects variant profile',
      'User configures AI provider',
      'User exports or imports state',
      'User resets local state',
    ],
    defaultAiAgentNeeds: ['apiConfigAgent'],
    defaultApiIntegrationNeeds: [],
    defaultUILayoutProfile: 'sidebar-shell',
    defaultStateMode: 'local-first',
    defaultSafetyLevel: 'standard',
    recommendedFutureRuns: ['Run 2: Blueprint Engine', 'Run 3: AI Agents', 'Run 4: Supabase Sync'],
    lockedRules: [
      'Do not replace storage.js.',
      'Do not create duplicate SSOT.',
      'Do not remove foundation pages.',
    ],
  },
  {
    id: 'learningPlatform',
    name: 'Learning Platform',
    productType: 'lms',
    description: 'Production LMS with course delivery, student progress tracking, and instructor tooling.',
    defaultCoreModules: ['dashboard', 'learning', 'admin', 'reports'],
    defaultOptionalModules: ['aiAgents', 'integrations'],
    defaultDataEntities: ['Course', 'Lesson', 'Student', 'Enrollment', 'Progress', 'Assessment'],
    defaultUserFlows: [
      'Student browses and enrols in courses',
      'Student completes lessons and assessments',
      'Instructor creates and publishes courses',
      'Admin manages students and reports',
      'AI agent provides learning recommendations',
    ],
    defaultAiAgentNeeds: ['learningRecommendationAgent', 'validationAgent'],
    defaultApiIntegrationNeeds: ['video-hosting', 'email-notifications'],
    defaultUILayoutProfile: 'sidebar-shell',
    defaultStateMode: 'supabase',
    defaultSafetyLevel: 'standard',
    recommendedFutureRuns: [
      'Run 3: AI Agent Panels',
      'Run 4: Supabase Sync + Course Engine',
      'Run 5: Student Portal + Assessment Engine',
    ],
    lockedRules: [
      'Course engine must be built separate from shell.',
      'Student data must be isolated per user (RLS).',
      'No course data in local-only mode.',
    ],
  },
  {
    id: 'projectControlOS',
    name: 'Project Control OS',
    productType: 'project-management',
    description: 'Production project, task, and team control operating system.',
    defaultCoreModules: ['dashboard', 'projects', 'admin', 'reports'],
    defaultOptionalModules: ['aiAgents', 'integrations', 'monitoring'],
    defaultDataEntities: ['Project', 'Task', 'TeamMember', 'Milestone', 'TimeLog', 'Comment'],
    defaultUserFlows: [
      'User creates and manages projects',
      'User assigns tasks to team members',
      'User tracks milestones and progress',
      'Admin generates project reports',
      'AI agent provides task prioritisation guidance',
    ],
    defaultAiAgentNeeds: ['systemArchitectAgent', 'validationAgent'],
    defaultApiIntegrationNeeds: ['calendar-sync', 'slack-notifications', 'github-issues'],
    defaultUILayoutProfile: 'kanban-shell',
    defaultStateMode: 'supabase',
    defaultSafetyLevel: 'standard',
    recommendedFutureRuns: [
      'Run 3: AI Agent Panels',
      'Run 4: Supabase + Task Engine',
      'Run 5: Team Portal + Time Tracking',
    ],
    lockedRules: [
      'No fleet logic.',
      'No LMS course logic.',
      'Role-based access required.',
    ],
  },
  {
    id: 'fleetDashboard',
    name: 'Fleet / Routing Dashboard',
    productType: 'fleet',
    description: 'Safety-critical vehicle fleet and route management dashboard.',
    defaultCoreModules: ['dashboard', 'fleet', 'monitoring', 'admin', 'reports'],
    defaultOptionalModules: ['integrations'],
    defaultDataEntities: ['Vehicle', 'Driver', 'Route', 'Trip', 'Incident', 'MaintenanceLog'],
    defaultUserFlows: [
      'Dispatcher assigns drivers to routes',
      'Driver logs trip start and end',
      'Manager monitors live fleet status',
      'Admin generates fleet reports',
      'System alerts on vehicle incidents',
    ],
    defaultAiAgentNeeds: ['safetyComplianceAgent'],
    defaultApiIntegrationNeeds: ['maps-api', 'telematics-api', 'sms-alerts'],
    defaultUILayoutProfile: 'map-shell',
    defaultStateMode: 'supabase',
    defaultSafetyLevel: 'safety-critical',
    recommendedFutureRuns: [
      'Run 4: Supabase + Fleet Engine',
      'Run 5: Live Tracking + Alert System',
      'Run 6: Driver Portal',
    ],
    lockedRules: [
      'Safety-critical: all route changes must be logged.',
      'No LMS modules.',
      'No payment logic in fleet core.',
      'Driver data must comply with privacy regulations.',
    ],
  },
  {
    id: 'monitoringDashboard',
    name: 'Monitoring Dashboard',
    productType: 'monitoring',
    description: 'System, network, or operational health monitoring dashboard with live alerting.',
    defaultCoreModules: ['dashboard', 'monitoring', 'reports', 'admin'],
    defaultOptionalModules: ['integrations', 'aiAgents'],
    defaultDataEntities: ['SystemNode', 'MetricSnapshot', 'Alert', 'Incident', 'StatusHistory'],
    defaultUserFlows: [
      'Operator views live system health',
      'System triggers alert on threshold breach',
      'Admin acknowledges and resolves incidents',
      'User exports status report',
    ],
    defaultAiAgentNeeds: ['validationAgent'],
    defaultApiIntegrationNeeds: ['webhook-alerts', 'monitoring-api', 'slack-notifications'],
    defaultUILayoutProfile: 'data-grid-shell',
    defaultStateMode: 'hybrid',
    defaultSafetyLevel: 'sensitive',
    recommendedFutureRuns: [
      'Run 4: Supabase + Live Metrics Engine',
      'Run 5: Alert Management System',
    ],
    lockedRules: [
      'Read-only views by default.',
      'Alert thresholds must be configurable.',
      'No destructive actions from monitoring views.',
    ],
  },
  {
    id: 'clientPortal',
    name: 'Client Portal',
    productType: 'portal',
    description: 'Production client-facing self-service and project communication portal.',
    defaultCoreModules: ['dashboard', 'projects', 'integrations', 'settings'],
    defaultOptionalModules: ['reports', 'aiAgents'],
    defaultDataEntities: ['Client', 'Project', 'Message', 'Document', 'Invoice'],
    defaultUserFlows: [
      'Client logs in and views project status',
      'Client downloads documents and invoices',
      'Client sends messages to team',
      'Admin manages client access',
    ],
    defaultAiAgentNeeds: ['uxLogicAgent'],
    defaultApiIntegrationNeeds: ['email-notifications', 'document-storage', 'payment-gateway'],
    defaultUILayoutProfile: 'portal-shell',
    defaultStateMode: 'supabase',
    defaultSafetyLevel: 'sensitive',
    recommendedFutureRuns: [
      'Run 4: Supabase + Auth + Client Engine',
      'Run 5: Messaging + Document System',
    ],
    lockedRules: [
      'Role separation required: client vs admin.',
      'No admin routes exposed to clients.',
      'Client data isolation with RLS.',
    ],
  },
  {
    id: 'adminDashboard',
    name: 'Admin Dashboard',
    productType: 'admin',
    description: 'Production internal administration and team management dashboard.',
    defaultCoreModules: ['dashboard', 'admin', 'reports', 'integrations', 'settings'],
    defaultOptionalModules: ['aiAgents', 'monitoring'],
    defaultDataEntities: ['User', 'Role', 'AuditLog', 'SystemConfig', 'Report'],
    defaultUserFlows: [
      'Admin manages user accounts and roles',
      'Admin views audit logs',
      'Admin configures system settings',
      'Admin generates and exports reports',
    ],
    defaultAiAgentNeeds: ['validationAgent', 'systemArchitectAgent'],
    defaultApiIntegrationNeeds: ['email-notifications', 'audit-log-api'],
    defaultUILayoutProfile: 'sidebar-shell',
    defaultStateMode: 'supabase',
    defaultSafetyLevel: 'sensitive',
    recommendedFutureRuns: [
      'Run 4: Supabase + Auth + User Management',
      'Run 5: Audit Log + Reporting Engine',
    ],
    lockedRules: [
      'Admin-only access.',
      'All admin actions must be audited.',
      'No public-facing routes.',
    ],
  },
  {
    id: 'aiAnalysisPlatform',
    name: 'AI Analysis Platform',
    productType: 'ai-analysis',
    description: 'Production AI-assisted data analysis, insight generation, and reporting platform.',
    defaultCoreModules: ['dashboard', 'aiConfig', 'aiAgents', 'reports', 'admin'],
    defaultOptionalModules: ['integrations', 'monitoring'],
    defaultDataEntities: ['DataSet', 'AnalysisRun', 'InsightReport', 'ModelConfig', 'UserQuery'],
    defaultUserFlows: [
      'User connects or uploads a data source',
      'User selects AI model and analysis type',
      'System generates insight report',
      'User reviews and exports insights',
      'Admin manages AI model configurations',
    ],
    defaultAiAgentNeeds: ['systemArchitectAgent', 'validationAgent', 'uxLogicAgent'],
    defaultApiIntegrationNeeds: ['ai-api', 'data-storage', 'export-api'],
    defaultUILayoutProfile: 'analysis-shell',
    defaultStateMode: 'hybrid',
    defaultSafetyLevel: 'sensitive',
    recommendedFutureRuns: [
      'Run 3: AI Agent Panels',
      'Run 4: Supabase + Data Engine',
      'Run 5: Analysis Pipeline + Report Builder',
    ],
    lockedRules: [
      'No autonomous AI actions without explicit user approval.',
      'No raw keys in exported reports.',
      'AI model configs must be validated before use.',
    ],
  },
  {
    id: 'employeeInductionPlatform',
    name: 'Employee Induction Platform',
    productType: 'induction',
    description: 'Compliance-critical workplace onboarding, induction, and work readiness tracker.',
    defaultCoreModules: ['dashboard', 'learning', 'admin', 'reports'],
    defaultOptionalModules: ['integrations', 'monitoring'],
    defaultDataEntities: ['Employee', 'InductionModule', 'CompletionRecord', 'Certificate', 'Department'],
    defaultUserFlows: [
      'New employee completes onboarding modules',
      'HR tracks induction completion',
      'Manager reviews team readiness',
      'Admin generates compliance reports',
    ],
    defaultAiAgentNeeds: ['validationAgent', 'safetyComplianceAgent'],
    defaultApiIntegrationNeeds: ['email-notifications', 'hr-system-api'],
    defaultUILayoutProfile: 'sidebar-shell',
    defaultStateMode: 'supabase',
    defaultSafetyLevel: 'compliance-critical',
    recommendedFutureRuns: [
      'Run 4: Supabase + HR Engine',
      'Run 5: Certificate System + Compliance Reports',
    ],
    lockedRules: [
      'HR-safe: no private employee data in exports without consent.',
      'Completion records must be immutable once signed.',
      'Compliance reporting must meet local standards.',
    ],
  },
  {
    id: 'portfolioDemoSystem',
    name: 'Portfolio-Ready Product System',
    productType: 'portfolio',
    description: 'Production-ready product showcase system for presenting product variants to clients.',
    defaultCoreModules: ['dashboard', 'variantProfile', 'modules', 'settings', 'blueprintEngine'],
    defaultOptionalModules: ['aiConfig'],
    defaultDataEntities: ['ShowcaseConfig', 'ProductVariant', 'ClientPresentation'],
    defaultUserFlows: [
      'User browses available product variants',
      'User switches between product transformation targets',
      'Owner configures showcase settings',
      'Owner presents product capabilities in client sessions',
    ],
    defaultAiAgentNeeds: ['productStrategyAgent'],
    defaultApiIntegrationNeeds: [],
    defaultUILayoutProfile: 'showcase-shell',
    defaultStateMode: 'local-first',
    defaultSafetyLevel: 'standard',
    recommendedFutureRuns: [
      'Run 3: AI Agent Panels',
      'Run 5: Showcase Polish + Client Presentation Mode',
    ],
    lockedRules: [
      'No real customer data without explicit consent.',
      'No raw API keys in any presentation configuration.',
      'No destructive actions during client presentations.',
    ],
  },
  {
    id: 'customProductSystem',
    name: 'Custom Product System',
    productType: 'custom',
    description: 'A fully custom production system defined by the product owner.',
    defaultCoreModules: ['dashboard', 'settings'],
    defaultOptionalModules: ['modules', 'aiConfig', 'variantProfile'],
    defaultDataEntities: [],
    defaultUserFlows: [],
    defaultAiAgentNeeds: [],
    defaultApiIntegrationNeeds: [],
    defaultUILayoutProfile: 'sidebar-shell',
    defaultStateMode: 'local-first',
    defaultSafetyLevel: 'standard',
    recommendedFutureRuns: ['Define in next run based on product requirements.'],
    lockedRules: [
      'Product owner must define all modules and data entities.',
      'Do not replicate proprietary third-party applications.',
    ],
  },
];

/**
 * Get preset by id.
 */
export function getPresetById(id) {
  return blueprintPresets.find((p) => p.id === id) || null;
}

export default blueprintPresets;
