// 4P3X Module Registry — RUN 1 + RUN 2 + RUN 3 + RUN 4
// Navigation MUST be driven from this file only.

const moduleRegistry = [
  // ─── Run 1 Active ────────────────────────────────────────────────────
  {
    id: 'dashboard',
    label: 'Dashboard',
    description: 'System overview, health, and identity summary.',
    status: 'active', route: '/', icon: 'LayoutDashboard',
    canEnable: true, runToBuild: 'Run 1',
  },
  {
    id: 'modules',
    label: 'Modules',
    description: 'Browse active and reserved module slots.',
    status: 'active', route: '/modules', icon: 'Boxes',
    canEnable: true, runToBuild: 'Run 1',
  },
  {
    id: 'variantProfile',
    label: 'Variant Profile',
    description: 'Select and manage product transformation profiles.',
    status: 'active', route: '/variant-profile', icon: 'Layers',
    canEnable: true, runToBuild: 'Run 1',
  },
  {
    id: 'aiConfig',
    label: 'AI Config',
    description: 'Configure external AI API provider and built-in agent registry.',
    status: 'active', route: '/ai-config', icon: 'BrainCircuit',
    canEnable: true, runToBuild: 'Run 1',
  },
  {
    id: 'settings',
    label: 'Settings',
    description: 'App identity, state management, export/import, and reset.',
    status: 'active', route: '/settings', icon: 'Settings',
    canEnable: true, runToBuild: 'Run 1',
  },
  // ─── Run 2 Active ────────────────────────────────────────────────────
  {
    id: 'blueprintEngine',
    label: 'Blueprint Engine',
    description: 'Create, manage, and export product blueprint definitions.',
    status: 'active', route: '/blueprints', icon: 'FileCode',
    canEnable: true, runToBuild: 'Run 2',
  },
  {
    id: 'blueprintDetail',
    label: 'Blueprint Detail',
    description: 'Edit, validate, and score an individual product blueprint.',
    status: 'active', route: '/blueprint-detail', icon: 'FileSearch',
    canEnable: true, runToBuild: 'Run 2',
  },
  {
    id: 'transformationReadiness',
    label: 'Transformation Readiness',
    description: 'Evaluate transformation readiness and view rule checklist.',
    status: 'active', route: '/readiness', icon: 'Gauge',
    canEnable: true, runToBuild: 'Run 2',
  },
  // ─── Run 3 Active ────────────────────────────────────────────────────
  {
    id: 'aiAgents',
    label: 'Internal AI Agents',
    description: 'Safe advisory internal agents for architecture, validation, UX, transformation, API, and compliance guidance.',
    status: 'active', route: '/ai-agents', icon: 'Bot',
    canEnable: true, runToBuild: 'Run 3',
  },
  {
    id: 'agentWorkbench',
    label: 'Agent Workbench',
    description: 'Controlled workbench for running advisory analysis against active blueprints and transformation readiness.',
    status: 'active', route: '/agent-workbench', icon: 'FlaskConical',
    canEnable: true, runToBuild: 'Run 3',
  },
  {
    id: 'agentRecommendations',
    label: 'Agent Recommendations',
    description: 'Local recommendation queue generated by advisory agents.',
    status: 'active', route: '/agent-recommendations', icon: 'ListChecks',
    canEnable: true, runToBuild: 'Run 3',
  },
  // ─── Run 4 Active — Transformation Compiler ───────────────────────────
  {
    id: 'transformationCompiler',
    label: 'Transformation Compiler',
    description: 'Converts validated blueprints into safe, non-destructive product skeleton plans.',
    status: 'active', route: '/transformation-compiler', icon: 'Cpu',
    canEnable: true, runToBuild: 'Run 4',
  },
  {
    id: 'productSkeletonGenerator',
    label: 'Product Skeleton Generator',
    description: 'Generates production-ready skeleton plans for future variant builds without writing files automatically.',
    status: 'active', route: '/product-skeleton-generator', icon: 'Layers',
    canEnable: true, runToBuild: 'Run 4',
  },
  {
    id: 'transformationPlanDetail',
    label: 'Transformation Plan Detail',
    description: 'Detailed view of generated skeleton structure, risks, modules, state plans, UI plans, and future run sequence.',
    status: 'active', route: '/transformation-plan-detail', icon: 'FileSearch',
    canEnable: true, runToBuild: 'Run 4',
  },
  // ─── Reserved (future runs) ───────────────────────────────────────────
  {
    id: 'learning',
    label: 'Learning',
    description: 'LMS course engine and learning content delivery.',
    status: 'reserved', route: '/learning', icon: 'BookOpen',
    canEnable: false, runToBuild: 'Run 5',
  },
  {
    id: 'projects',
    label: 'Projects',
    description: 'Project and task control operating system.',
    status: 'reserved', route: '/projects', icon: 'FolderKanban',
    canEnable: false, runToBuild: 'Run 5',
  },
  {
    id: 'fleet',
    label: 'Fleet',
    description: 'Vehicle fleet and route management.',
    status: 'reserved', route: '/fleet', icon: 'Truck',
    canEnable: false, runToBuild: 'Run 5',
  },
  {
    id: 'monitoring',
    label: 'Monitoring',
    description: 'System and operational health monitoring.',
    status: 'reserved', route: '/monitoring', icon: 'Activity',
    canEnable: false, runToBuild: 'Run 5',
  },
  {
    id: 'admin',
    label: 'Admin',
    description: 'Internal administration and team management.',
    status: 'reserved', route: '/admin', icon: 'ShieldCheck',
    canEnable: false, runToBuild: 'Run 6',
  },
  {
    id: 'reports',
    label: 'Reports',
    description: 'Data reports and analytics exports.',
    status: 'reserved', route: '/reports', icon: 'BarChart3',
    canEnable: false, runToBuild: 'Run 6',
  },
  {
    id: 'integrations',
    label: 'Integrations',
    description: 'External service integrations and sync layer.',
    status: 'reserved', route: '/integrations', icon: 'Plug',
    canEnable: false, runToBuild: 'Run 7',
  },
,

  // ─── Run 5: Variant Build Launcher ──────────────────────────────────
  {
    id: 'variantBuildLauncher',
    label: 'Variant Build Launcher',
    description: 'Prepares selected product variants for controlled future build runs using validated transformation plans.',
    status: 'active', route: '/variant-build-launcher', icon: 'Rocket',
    canEnable: true, runToBuild: 'Run 5',
  },
  {
    id: 'runPromptGenerator',
    label: 'Run Prompt Generator',
    description: 'Generates isolated, copy-paste-ready run prompts for the selected product variant.',
    status: 'active', route: '/run-prompt-generator', icon: 'FileText',
    canEnable: true, runToBuild: 'Run 5',
  },
  {
    id: 'generatedPromptDetail',
    label: 'Generated Prompt Detail',
    description: 'Detailed view, validation, copy, export, and safety review for generated build prompts.',
    status: 'active', route: '/generated-prompt-detail', icon: 'FileSearch',
    canEnable: true, runToBuild: 'Run 5',
  },

  // ─── Run 6: Variant Workspace Manager ───────────────────────────────
  {
    id: 'variantWorkspaces',
    label: 'Variant Workspaces',
    description: 'Creates isolated workspaces for staging and tracking future product variant builds.',
    status: 'active', route: '/variant-workspaces', icon: 'Layers',
    canEnable: true, runToBuild: 'Run 6',
  },
  {
    id: 'workspaceDetail',
    label: 'Workspace Detail',
    description: 'Detailed view of a selected variant workspace, linked assets, locks, progress, and readiness.',
    status: 'active', route: '/workspace-detail', icon: 'FolderOpen',
    canEnable: true, runToBuild: 'Run 6',
  },
  {
    id: 'workspaceComparison',
    label: 'Workspace Comparison',
    description: 'Compares product variant workspaces without merging or contaminating their state.',
    status: 'active', route: '/workspace-comparison', icon: 'GitCompare',
    canEnable: true, runToBuild: 'Run 6',
  },
  {
    id: 'exportCentre',
    label: 'Export Centre',
    description: 'Creates safe export packs for reusable base handoff, builder tools, deployment preparation, and future product variant packages.',
    status: 'active', route: '/export-centre', icon: 'Package',
    canEnable: true, runToBuild: 'Run 7',
  },
  {
    id: 'handoffPackBuilder',
    label: 'Handoff Pack Builder',
    description: 'Builds structured handoff instructions for Base44, Manus, Replit, Cursor, GitHub, Vercel, and future variant workflows.',
    status: 'active', route: '/handoff-pack-builder', icon: 'FileText',
    canEnable: true, runToBuild: 'Run 7',
  },
  {
    id: 'deploymentReadiness',
    label: 'Deployment Readiness',
    description: 'Checks PWA, GitHub, Vercel, environment, and no-secrets readiness before export or deployment handoff.',
    status: 'active', route: '/deployment-readiness', icon: 'CheckCircle',
    canEnable: true, runToBuild: 'Run 7',
  },
  {
    id: 'exportPackDetail',
    label: 'Export Pack Detail',
    description: 'Detailed view of selected export pack, linked assets, readiness, sanitisation, and handoff instructions.',
    status: 'active', route: '/export-pack-detail', icon: 'Eye',
    canEnable: true, runToBuild: 'Run 7',
  },
  // ── Run 8: Final Audit + Production Hardening + Transformation Readiness Lock ──
  {
    id: 'finalSystemAudit',
    label: 'Final System Audit',
    description: 'Runs complete audit checks across routes, modules, SSOT, state, agents, transformation, exports, and readiness.',
    status: 'active', route: '/final-system-audit', icon: 'ShieldCheck',
    canEnable: true, runToBuild: 'Run 8',
  },
  {
    id: 'productionHardening',
    label: 'Production Hardening',
    description: 'Applies final hardening checks for local-first safety, no-secrets export, no destructive automation, and transformation stability.',
    status: 'active', route: '/production-hardening', icon: 'ListChecks',
    canEnable: true, runToBuild: 'Run 8',
  },
  {
    id: 'transformationReadinessLock',
    label: 'Transformation Readiness Lock',
    description: 'Locks or blocks the base from real variant transformation based on final audit results.',
    status: 'active', route: '/transformation-readiness-lock', icon: 'Gauge',
    canEnable: true, runToBuild: 'Run 8',
  },
  {
    id: 'finalReadinessReport',
    label: 'Final Readiness Report',
    description: 'Final export-ready report showing whether the base is safe to use for real product variant builds.',
    status: 'active', route: '/final-readiness-report', icon: 'FileText',
    canEnable: true, runToBuild: 'Run 8',
  },

  // ── Run 9 — Base ZIP / Project Package Builder ──────────────────────────────
  {
    id: 'basePackageBuilder',
    label: 'Base Package Builder',
    description: 'Prepares the reusable base for safe zip packaging and builder-tool handoff.',
    status: 'active', route: '/base-package-builder', icon: 'Package',
    canEnable: true, runToBuild: 'Run 9',
  },
  {
    id: 'packageManifest',
    label: 'Package Manifest',
    description: 'Shows the final package file manifest, include/exclude rules, branding, and handoff metadata.',
    status: 'active', route: '/package-manifest', icon: 'ScrollText',
    canEnable: true, runToBuild: 'Run 9',
  },
  {
    id: 'packageValidation',
    label: 'Package Validation',
    description: 'Validates the reusable base package before zip export or builder handoff.',
    status: 'active', route: '/package-validation', icon: 'ShieldCheck',
    canEnable: true, runToBuild: 'Run 9',
  },
  // ── Run 10 — Master Variant Transformation Launcher ─────────────────────────
  {
    id: 'masterVariantLauncher',
    label: 'Master Variant Launcher',
    description: 'Creates final transformation prompts for building separate product variants from the packaged reusable base.',
    status: 'active', route: '/master-variant-launcher', icon: 'Rocket',
    canEnable: true, runToBuild: 'Run 10',
  },
  {
    id: 'variantTransformationPromptBuilder',
    label: 'Variant Transformation Prompt Builder',
    description: 'Builds strict, copy-paste-ready prompts for creating one selected product variant from the base zip.',
    status: 'active', route: '/variant-transformation-prompt-builder', icon: 'FileCode',
    canEnable: true, runToBuild: 'Run 10',
  },
  {
    id: 'finalBaseCompletion',
    label: 'Final Base Completion',
    description: 'Locks the reusable base as complete and ready for separate product variant builds.',
    status: 'active', route: '/final-base-completion', icon: 'CheckCircle',
    canEnable: true, runToBuild: 'Run 10',
  },
];

export function getActiveModules()      { return moduleRegistry.filter((m) => m.status === 'active'); }
export function getReservedModules()    { return moduleRegistry.filter((m) => m.status === 'reserved'); }
export function getModuleByRoute(route) { return moduleRegistry.find((m) => m.route === route) || null; }
export function getModulesByRun(run)    { return moduleRegistry.filter((m) => m.runToBuild === run); }

export default moduleRegistry;
