// 4P3X Product Run Sequences — Run 5
// Defines future run sequences for each supported product type.
// These sequences are PLANNING DATA ONLY — they do not build product variants.
// Generated prompts reference these sequences; builds must be executed manually.

export const PRODUCT_RUN_SEQUENCES = {

  learningPlatform: {
    productType: 'learningPlatform',
    productLabel: 'Learning Platform',
    runs: [
      {
        runNumber: 'Run 6',
        title: 'Learning Data Model + Module Shell',
        mission: 'Create the core learning data model (courses, modules, lessons, progress, users) and the top-level module shell. No UI logic yet.',
        dependsOn: ['Run 1', 'Run 2', 'Run 3', 'Run 4', 'Run 5'],
        allowedFiles: [
          'src/state/initialState.js',
          'src/state/storage.js',
          'src/config/moduleRegistry.js',
          'src/pages/Learning.jsx',
          'src/components/learning/',
          'src/logic/learning/',
          'src/utils/learningUtils.js',
        ],
        forbiddenFiles: [
          'src/state/storage.js (full rewrite)',
          'src/config/appConfig.js',
          'src/logic/agents/',
          'src/logic/transformer/',
          'src/logic/launcher/',
          'src/pages/Dashboard.jsx (structural rewrite)',
          'public/',
          '.env',
        ],
        requiredModules: ['learning'],
        requiredDataModels: ['Course', 'Module', 'Lesson', 'LearnerProgress', 'CourseEnrollment'],
        requiredUiScreens: ['LearningDashboard', 'CourseList'],
        requiredStateTransitions: ['loadLearningModules', 'saveLearningProgress'],
        requiredValidation: [
          'Storage.js SSOT extended safely',
          'No LMS-specific engine overwriting agent system',
          'Course data model uses correct schema',
        ],
        stopConditions: [
          'Request would overwrite agentSystem or transformationCompiler state',
          'Request introduces Supabase before its designated run',
          'Request builds lesson player UI in this run',
        ],
        rollbackGuidance: [
          'Remove learning-specific state from initialState.js',
          'Remove Learning page route from routes.js',
          'Remove learning entries from moduleRegistry.js',
        ],
        acceptanceCriteria: [
          'Course data model persists via storage.js',
          'Learning module appears in sidebar',
          'No existing runs break',
          'Build passes without errors',
        ],
      },
      {
        runNumber: 'Run 7',
        title: 'Course/Module/Lesson Builder',
        mission: 'Build the course creation UI, module builder, and lesson editor. Admin-only create/edit flow. No payment or certificate logic yet.',
        dependsOn: ['Run 6'],
        allowedFiles: [
          'src/pages/CourseBuilder.jsx',
          'src/components/learning/',
          'src/logic/learning/courseBuilder.js',
          'src/state/storage.js (extend only)',
        ],
        forbiddenFiles: [
          'src/logic/launcher/',
          'src/logic/transformer/',
          'src/logic/agents/',
          'src/state/initialState.js (structural rewrite)',
        ],
        requiredModules: ['courseBuilder'],
        requiredDataModels: ['CourseSection', 'LessonContent', 'MediaAsset'],
        requiredUiScreens: ['CourseBuilderPage', 'LessonEditor', 'ModuleManager'],
        requiredStateTransitions: ['createCourse', 'editLesson', 'publishModule'],
        requiredValidation: [
          'Course builder does not overwrite learning data model from Run 6',
          'Admin-only write path enforced',
        ],
        stopConditions: [
          'Request builds payment or certificate logic in this run',
          'Request overwrites Run 6 data models',
        ],
        rollbackGuidance: [
          'Remove course builder pages',
          'Remove courseBuilder logic',
          'Restore Run 6 state only',
        ],
        acceptanceCriteria: [
          'Admin can create and edit a course',
          'Lessons persist via storage.js',
          'No existing run breaks',
        ],
      },
      {
        runNumber: 'Run 8',
        title: 'Progress, Quiz, Certificate, Admin Import/Export',
        mission: 'Add learner progress tracking, quiz engine, certificate generation logic, and admin data import/export. No external AI grading yet.',
        dependsOn: ['Run 6', 'Run 7'],
        allowedFiles: [
          'src/pages/LearnerDashboard.jsx',
          'src/pages/QuizEngine.jsx',
          'src/pages/CertificateViewer.jsx',
          'src/components/learning/',
          'src/logic/learning/',
          'src/state/storage.js (extend only)',
        ],
        forbiddenFiles: [
          'src/logic/launcher/',
          'src/logic/transformer/',
          'src/logic/agents/',
        ],
        requiredModules: ['quizEngine', 'certificateViewer', 'adminImport'],
        requiredDataModels: ['QuizAttempt', 'Certificate', 'ProgressRecord'],
        requiredUiScreens: ['QuizPage', 'CertificatePage', 'LearnerProgressView'],
        requiredStateTransitions: ['submitQuiz', 'issueCertificate', 'importCourseData'],
        requiredValidation: [
          'Quiz does not overwrite lesson data',
          'Certificate generation is local-only',
          'Import validates data before saving',
        ],
        stopConditions: [
          'Request calls external AI grading API',
          'Request writes certificate PDFs to live app folders',
        ],
        rollbackGuidance: [
          'Remove quiz and certificate pages',
          'Remove progress tracking from storage',
          'Restore Run 7 state',
        ],
        acceptanceCriteria: [
          'Learner can complete a quiz',
          'Certificate is generated locally',
          'Progress persists via storage.js',
        ],
      },
    ],
  },

  projectControlOS: {
    productType: 'projectControlOS',
    productLabel: 'Project Control OS',
    runs: [
      {
        runNumber: 'Run 6',
        title: 'Project Registry + Run Tracker',
        mission: 'Create the project registry data model and run tracker. Each project tracks build runs, status, and prompts used.',
        dependsOn: ['Run 1', 'Run 2', 'Run 3', 'Run 4', 'Run 5'],
        allowedFiles: [
          'src/pages/ProjectRegistry.jsx',
          'src/components/projects/',
          'src/logic/projects/projectRegistry.js',
          'src/state/storage.js (extend only)',
          'src/state/initialState.js (extend only)',
          'src/config/moduleRegistry.js',
        ],
        forbiddenFiles: [
          'src/logic/agents/',
          'src/logic/transformer/',
          'src/logic/launcher/',
        ],
        requiredModules: ['projectRegistry'],
        requiredDataModels: ['Project', 'RunRecord', 'BuildRun'],
        requiredUiScreens: ['ProjectRegistryPage', 'RunTrackerView'],
        requiredStateTransitions: ['createProject', 'logBuildRun', 'updateRunStatus'],
        requiredValidation: [
          'Project data does not conflict with transformation plan IDs',
          'Run tracker uses storage.js SSOT',
        ],
        stopConditions: [
          'Request builds prompt vault in this run',
          'Request overwrites transformation compiler state',
        ],
        rollbackGuidance: [
          'Remove project registry state from initialState.js',
          'Remove project routes',
        ],
        acceptanceCriteria: [
          'Projects can be created and listed',
          'Build runs are tracked per project',
          'Build passes',
        ],
      },
      {
        runNumber: 'Run 7',
        title: 'Prompt Vault + Build History',
        mission: 'Build the prompt vault for storing used build prompts per project, with build history view and run diff comparison.',
        dependsOn: ['Run 6'],
        allowedFiles: [
          'src/pages/PromptVault.jsx',
          'src/pages/BuildHistory.jsx',
          'src/components/projects/',
          'src/logic/projects/',
          'src/state/storage.js (extend only)',
        ],
        forbiddenFiles: [
          'src/logic/launcher/',
          'src/logic/agents/',
        ],
        requiredModules: ['promptVault', 'buildHistory'],
        requiredDataModels: ['StoredPrompt', 'BuildDiff'],
        requiredUiScreens: ['PromptVaultPage', 'BuildHistoryPage'],
        requiredStateTransitions: ['savePromptToVault', 'loadBuildHistory'],
        requiredValidation: [
          'Prompt vault does not duplicate variantLauncher generatedPrompts',
          'Build history is append-only',
        ],
        stopConditions: [
          'Request builds error centre in this run',
          'Request auto-executes stored prompts',
        ],
        rollbackGuidance: [
          'Remove prompt vault pages and logic',
          'Restore Run 6 state',
        ],
        acceptanceCriteria: [
          'Prompts can be saved to vault',
          'Build history is viewable per project',
          'Build passes',
        ],
      },
      {
        runNumber: 'Run 8',
        title: 'Error Centre + Repair Queue + Deployment Tracking',
        mission: 'Add an error centre for tracking build issues, a repair queue for resolving them, and deployment readiness tracking per project.',
        dependsOn: ['Run 6', 'Run 7'],
        allowedFiles: [
          'src/pages/ErrorCentre.jsx',
          'src/pages/RepairQueue.jsx',
          'src/components/projects/',
          'src/logic/projects/',
          'src/state/storage.js (extend only)',
        ],
        forbiddenFiles: [
          'src/logic/launcher/',
          'src/logic/agents/',
        ],
        requiredModules: ['errorCentre', 'repairQueue'],
        requiredDataModels: ['BuildError', 'RepairTask', 'DeploymentRecord'],
        requiredUiScreens: ['ErrorCentrePage', 'RepairQueuePage'],
        requiredStateTransitions: ['logBuildError', 'resolveRepairTask', 'markDeploymentReady'],
        requiredValidation: [
          'Error centre does not overwrite project registry',
          'Repair queue is advisory only',
        ],
        stopConditions: [
          'Request auto-repairs build errors',
          'Request deploys to production in this run',
        ],
        rollbackGuidance: [
          'Remove error centre pages',
          'Restore Run 7 state',
        ],
        acceptanceCriteria: [
          'Build errors can be logged and tracked',
          'Repair tasks are manageable',
          'Deployment readiness is visible',
        ],
      },
    ],
  },

  fleetDashboard: {
    productType: 'fleetDashboard',
    productLabel: 'Fleet Dashboard',
    runs: [
      {
        runNumber: 'Run 6',
        title: 'Vehicle/Fleet Data Model + Dashboard Shell',
        mission: 'Create the fleet data model (vehicles, drivers, routes) and the fleet dashboard shell with summary KPIs.',
        dependsOn: ['Run 1', 'Run 2', 'Run 3', 'Run 4', 'Run 5'],
        allowedFiles: [
          'src/pages/FleetDashboard.jsx',
          'src/components/fleet/',
          'src/logic/fleet/',
          'src/state/storage.js (extend only)',
          'src/state/initialState.js (extend only)',
          'src/config/moduleRegistry.js',
        ],
        forbiddenFiles: [
          'src/logic/agents/',
          'src/logic/transformer/',
          'src/logic/launcher/',
        ],
        requiredModules: ['fleetDashboard'],
        requiredDataModels: ['Vehicle', 'Driver', 'Route', 'FleetEvent'],
        requiredUiScreens: ['FleetDashboardPage', 'VehicleList'],
        requiredStateTransitions: ['loadFleetData', 'updateVehicleStatus'],
        requiredValidation: [
          'Fleet data does not conflict with transformation plan schemas',
          'Dashboard shell uses SSOT',
        ],
        stopConditions: [
          'Request builds routing engine in this run',
          'Request calls live GPS APIs',
        ],
        rollbackGuidance: [
          'Remove fleet state from initialState.js',
          'Remove fleet routes',
        ],
        acceptanceCriteria: [
          'Fleet dashboard renders with vehicle list',
          'Vehicle status persists',
          'Build passes',
        ],
      },
      {
        runNumber: 'Run 7',
        title: 'Routing/Provider Config Foundation',
        mission: 'Build the routing configuration layer, provider config, and route assignment logic. No live map API calls yet.',
        dependsOn: ['Run 6'],
        allowedFiles: [
          'src/pages/RoutingConfig.jsx',
          'src/components/fleet/',
          'src/logic/fleet/routingConfig.js',
          'src/state/storage.js (extend only)',
        ],
        forbiddenFiles: [
          'src/logic/launcher/',
          'src/logic/agents/',
        ],
        requiredModules: ['routingConfig'],
        requiredDataModels: ['RouteConfig', 'ProviderConfig'],
        requiredUiScreens: ['RoutingConfigPage'],
        requiredStateTransitions: ['saveRouteConfig', 'assignRouteToVehicle'],
        requiredValidation: [
          'Routing config does not call external map APIs',
          'Provider config stored securely',
        ],
        stopConditions: [
          'Request calls live Google Maps or HERE API',
          'Request builds compliance layer in this run',
        ],
        rollbackGuidance: [
          'Remove routing config pages',
          'Restore Run 6 state',
        ],
        acceptanceCriteria: [
          'Routes can be configured',
          'Providers can be set up without API keys',
          'Build passes',
        ],
      },
      {
        runNumber: 'Run 8',
        title: 'Compliance/Safety Advisory Layer + Reports',
        mission: 'Add fleet compliance checks, safety advisory notices, and report generation. Advisory only — no automated enforcement.',
        dependsOn: ['Run 6', 'Run 7'],
        allowedFiles: [
          'src/pages/FleetCompliance.jsx',
          'src/pages/FleetReports.jsx',
          'src/components/fleet/',
          'src/logic/fleet/',
          'src/state/storage.js (extend only)',
        ],
        forbiddenFiles: [
          'src/logic/launcher/',
          'src/logic/agents/',
        ],
        requiredModules: ['fleetCompliance', 'fleetReports'],
        requiredDataModels: ['ComplianceRecord', 'SafetyNotice', 'FleetReport'],
        requiredUiScreens: ['FleetCompliancePage', 'FleetReportsPage'],
        requiredStateTransitions: ['logComplianceEvent', 'generateFleetReport'],
        requiredValidation: [
          'Compliance checks are advisory only',
          'Reports do not expose driver PII',
        ],
        stopConditions: [
          'Request auto-enforces compliance actions',
          'Request exports driver PII without consent flow',
        ],
        rollbackGuidance: [
          'Remove compliance and report pages',
          'Restore Run 7 state',
        ],
        acceptanceCriteria: [
          'Compliance records are loggable',
          'Fleet reports generate locally',
          'Build passes',
        ],
      },
    ],
  },

  monitoringDashboard: {
    productType: 'monitoringDashboard',
    productLabel: 'Monitoring Dashboard',
    runs: [
      {
        runNumber: 'Run 6',
        title: 'Monitoring Data Model + Alert Shell',
        mission: 'Create the monitoring data model (metrics, alerts, services) and the alert dashboard shell.',
        dependsOn: ['Run 1', 'Run 2', 'Run 3', 'Run 4', 'Run 5'],
        allowedFiles: [
          'src/pages/MonitoringDashboard.jsx',
          'src/components/monitoring/',
          'src/logic/monitoring/',
          'src/state/storage.js (extend only)',
          'src/state/initialState.js (extend only)',
          'src/config/moduleRegistry.js',
        ],
        forbiddenFiles: ['src/logic/agents/', 'src/logic/transformer/', 'src/logic/launcher/'],
        requiredModules: ['monitoringDashboard'],
        requiredDataModels: ['ServiceMetric', 'Alert', 'MonitoredService'],
        requiredUiScreens: ['MonitoringDashboardPage', 'AlertList'],
        requiredStateTransitions: ['loadMetrics', 'acknowledgeAlert'],
        requiredValidation: ['Monitoring data uses SSOT', 'No live polling APIs called'],
        stopConditions: ['Request calls live API polling service', 'Request builds incident responder'],
        rollbackGuidance: ['Remove monitoring state', 'Remove monitoring routes'],
        acceptanceCriteria: ['Alert list renders', 'Metrics persist via storage.js', 'Build passes'],
      },
      {
        runNumber: 'Run 7',
        title: 'Service Health Rules + Threshold Config',
        mission: 'Build health threshold configuration, service health rules engine (local), and health status indicators.',
        dependsOn: ['Run 6'],
        allowedFiles: [
          'src/pages/HealthRulesConfig.jsx',
          'src/components/monitoring/',
          'src/logic/monitoring/',
          'src/state/storage.js (extend only)',
        ],
        forbiddenFiles: ['src/logic/launcher/', 'src/logic/agents/'],
        requiredModules: ['healthRulesConfig'],
        requiredDataModels: ['HealthRule', 'ThresholdConfig'],
        requiredUiScreens: ['HealthRulesPage'],
        requiredStateTransitions: ['saveHealthRule', 'evaluateServiceHealth'],
        requiredValidation: ['Health rules are local-only', 'No external alerting APIs'],
        stopConditions: ['Request calls PagerDuty or external alerting', 'Request auto-resolves incidents'],
        rollbackGuidance: ['Remove health rules pages', 'Restore Run 6 state'],
        acceptanceCriteria: ['Health rules can be created', 'Service status evaluates locally', 'Build passes'],
      },
      {
        runNumber: 'Run 8',
        title: 'Incident Log + Report Generator',
        mission: 'Add incident logging, resolution tracking, and local report generation for monitoring history.',
        dependsOn: ['Run 6', 'Run 7'],
        allowedFiles: [
          'src/pages/IncidentLog.jsx',
          'src/pages/MonitoringReports.jsx',
          'src/components/monitoring/',
          'src/logic/monitoring/',
          'src/state/storage.js (extend only)',
        ],
        forbiddenFiles: ['src/logic/launcher/', 'src/logic/agents/'],
        requiredModules: ['incidentLog', 'monitoringReports'],
        requiredDataModels: ['Incident', 'ResolutionRecord'],
        requiredUiScreens: ['IncidentLogPage', 'MonitoringReportsPage'],
        requiredStateTransitions: ['logIncident', 'resolveIncident', 'generateMonitoringReport'],
        requiredValidation: ['Incident log is append-only', 'Reports are local-only'],
        stopConditions: ['Request auto-resolves incidents', 'Request deploys monitoring agent'],
        rollbackGuidance: ['Remove incident pages', 'Restore Run 7 state'],
        acceptanceCriteria: ['Incidents can be logged', 'Reports generate locally', 'Build passes'],
      },
    ],
  },

  clientPortal: {
    productType: 'clientPortal',
    productLabel: 'Client Portal',
    runs: [
      {
        runNumber: 'Run 6',
        title: 'Client Data Model + Portal Shell',
        mission: 'Create the client data model (clients, contacts, projects) and the portal shell with client list and summary view.',
        dependsOn: ['Run 1', 'Run 2', 'Run 3', 'Run 4', 'Run 5'],
        allowedFiles: [
          'src/pages/ClientPortal.jsx',
          'src/components/portal/',
          'src/logic/portal/',
          'src/state/storage.js (extend only)',
          'src/state/initialState.js (extend only)',
          'src/config/moduleRegistry.js',
        ],
        forbiddenFiles: ['src/logic/agents/', 'src/logic/transformer/', 'src/logic/launcher/'],
        requiredModules: ['clientPortal'],
        requiredDataModels: ['Client', 'Contact', 'PortalProject'],
        requiredUiScreens: ['ClientListPage', 'ClientDetailPage'],
        requiredStateTransitions: ['loadClients', 'createClient', 'updateClient'],
        requiredValidation: ['Client data uses SSOT', 'No external CRM sync yet'],
        stopConditions: ['Request calls external CRM API', 'Request builds invoice engine in this run'],
        rollbackGuidance: ['Remove client portal state', 'Remove portal routes'],
        acceptanceCriteria: ['Client list renders', 'Clients persist via storage.js', 'Build passes'],
      },
      {
        runNumber: 'Run 7',
        title: 'Document Sharing + Task Tracker',
        mission: 'Add document upload/listing, task assignment per client, and client-facing status view.',
        dependsOn: ['Run 6'],
        allowedFiles: [
          'src/pages/ClientDocuments.jsx',
          'src/pages/ClientTasks.jsx',
          'src/components/portal/',
          'src/logic/portal/',
          'src/state/storage.js (extend only)',
        ],
        forbiddenFiles: ['src/logic/launcher/', 'src/logic/agents/'],
        requiredModules: ['clientDocuments', 'clientTasks'],
        requiredDataModels: ['Document', 'ClientTask'],
        requiredUiScreens: ['DocumentsPage', 'TaskTrackerPage'],
        requiredStateTransitions: ['uploadDocument', 'createTask', 'completeTask'],
        requiredValidation: ['Documents stored locally or with safe upload', 'Task tracker uses SSOT'],
        stopConditions: ['Request builds payment invoicing in this run'],
        rollbackGuidance: ['Remove document and task pages', 'Restore Run 6 state'],
        acceptanceCriteria: ['Documents can be listed', 'Tasks can be managed', 'Build passes'],
      },
      {
        runNumber: 'Run 8',
        title: 'Invoice + Reporting + Client Access Layer',
        mission: 'Add invoice generation, client reporting, and access control layer for multi-client portals.',
        dependsOn: ['Run 6', 'Run 7'],
        allowedFiles: [
          'src/pages/ClientInvoices.jsx',
          'src/pages/ClientReports.jsx',
          'src/components/portal/',
          'src/logic/portal/',
          'src/state/storage.js (extend only)',
        ],
        forbiddenFiles: ['src/logic/launcher/', 'src/logic/agents/'],
        requiredModules: ['clientInvoices', 'clientReports'],
        requiredDataModels: ['Invoice', 'ClientReport', 'AccessRule'],
        requiredUiScreens: ['InvoicePage', 'ClientReportsPage'],
        requiredStateTransitions: ['createInvoice', 'generateClientReport'],
        requiredValidation: ['Invoices are local-only unless payment run is added', 'Access rules validated before saving'],
        stopConditions: ['Request calls payment processor in this run without payment run'],
        rollbackGuidance: ['Remove invoice pages', 'Restore Run 7 state'],
        acceptanceCriteria: ['Invoices can be generated locally', 'Reports render', 'Build passes'],
      },
    ],
  },

  adminDashboard: {
    productType: 'adminDashboard',
    productLabel: 'Admin Dashboard',
    runs: [
      {
        runNumber: 'Run 6',
        title: 'Admin Data Model + Dashboard Shell',
        mission: 'Create the admin data model (users, roles, permissions) and the admin dashboard shell.',
        dependsOn: ['Run 1', 'Run 2', 'Run 3', 'Run 4', 'Run 5'],
        allowedFiles: [
          'src/pages/AdminDashboard.jsx',
          'src/components/admin/',
          'src/logic/admin/',
          'src/state/storage.js (extend only)',
          'src/state/initialState.js (extend only)',
          'src/config/moduleRegistry.js',
        ],
        forbiddenFiles: ['src/logic/agents/', 'src/logic/transformer/', 'src/logic/launcher/'],
        requiredModules: ['adminDashboard'],
        requiredDataModels: ['AdminUser', 'Role', 'Permission'],
        requiredUiScreens: ['AdminDashboardPage', 'UserManagementPage'],
        requiredStateTransitions: ['loadAdminUsers', 'updateUserRole'],
        requiredValidation: ['Admin state uses SSOT', 'Permission model validated before save'],
        stopConditions: ['Request builds analytics engine in this run', 'Request calls auth providers'],
        rollbackGuidance: ['Remove admin state', 'Remove admin routes'],
        acceptanceCriteria: ['Admin dashboard renders', 'User list manageable', 'Build passes'],
      },
      {
        runNumber: 'Run 7',
        title: 'Content Manager + Config Editor',
        mission: 'Build the admin content management interface and system config editor with role-gated access.',
        dependsOn: ['Run 6'],
        allowedFiles: [
          'src/pages/ContentManager.jsx',
          'src/pages/ConfigEditor.jsx',
          'src/components/admin/',
          'src/logic/admin/',
          'src/state/storage.js (extend only)',
        ],
        forbiddenFiles: ['src/logic/launcher/', 'src/logic/agents/'],
        requiredModules: ['contentManager', 'configEditor'],
        requiredDataModels: ['ContentItem', 'SystemConfig'],
        requiredUiScreens: ['ContentManagerPage', 'ConfigEditorPage'],
        requiredStateTransitions: ['createContent', 'updateSystemConfig'],
        requiredValidation: ['Config editor validates before save', 'No raw secrets in config'],
        stopConditions: ['Request exposes system secrets in config editor', 'Request builds report engine in this run'],
        rollbackGuidance: ['Remove content manager pages', 'Restore Run 6 state'],
        acceptanceCriteria: ['Content can be managed', 'Config editable with validation', 'Build passes'],
      },
      {
        runNumber: 'Run 8',
        title: 'Audit Log + Reports + Admin Export',
        mission: 'Add admin audit logging, activity reports, and safe admin data export.',
        dependsOn: ['Run 6', 'Run 7'],
        allowedFiles: [
          'src/pages/AuditLog.jsx',
          'src/pages/AdminReports.jsx',
          'src/components/admin/',
          'src/logic/admin/',
          'src/state/storage.js (extend only)',
        ],
        forbiddenFiles: ['src/logic/launcher/', 'src/logic/agents/'],
        requiredModules: ['auditLog', 'adminReports'],
        requiredDataModels: ['AuditEntry', 'AdminReport'],
        requiredUiScreens: ['AuditLogPage', 'AdminReportsPage'],
        requiredStateTransitions: ['logAdminAction', 'generateAdminReport'],
        requiredValidation: ['Audit log is append-only', 'Export sanitized before download'],
        stopConditions: ['Request exposes secrets in export', 'Request auto-deletes audit records'],
        rollbackGuidance: ['Remove audit pages', 'Restore Run 7 state'],
        acceptanceCriteria: ['Audit entries logged', 'Reports generated', 'Export sanitized', 'Build passes'],
      },
    ],
  },

  aiAnalysisPlatform: {
    productType: 'aiAnalysisPlatform',
    productLabel: 'AI Analysis Platform',
    runs: [
      {
        runNumber: 'Run 6',
        title: 'Analysis Data Model + Provider Config Shell',
        mission: 'Create the analysis data model (analyses, datasets, results) and the AI provider config shell. No live API calls yet.',
        dependsOn: ['Run 1', 'Run 2', 'Run 3', 'Run 4', 'Run 5'],
        allowedFiles: [
          'src/pages/AnalysisDashboard.jsx',
          'src/components/analysis/',
          'src/logic/analysis/',
          'src/state/storage.js (extend only)',
          'src/state/initialState.js (extend only)',
          'src/config/moduleRegistry.js',
        ],
        forbiddenFiles: ['src/logic/agents/', 'src/logic/transformer/', 'src/logic/launcher/'],
        requiredModules: ['analysisDashboard'],
        requiredDataModels: ['AnalysisJob', 'Dataset', 'AnalysisResult'],
        requiredUiScreens: ['AnalysisDashboardPage', 'DatasetList'],
        requiredStateTransitions: ['createAnalysisJob', 'loadDatasets'],
        requiredValidation: ['API keys stored securely through AI config', 'No live API calls in this run'],
        stopConditions: ['Request calls OpenAI or other AI provider in this run', 'Request builds ML training pipeline'],
        rollbackGuidance: ['Remove analysis state', 'Remove analysis routes'],
        acceptanceCriteria: ['Analysis dashboard renders', 'Jobs tracked via storage.js', 'Build passes'],
      },
      {
        runNumber: 'Run 7',
        title: 'Analysis Runner + Result Viewer',
        mission: 'Build the analysis job runner UI, provider API connection layer, and result viewer. API key required by user.',
        dependsOn: ['Run 6'],
        allowedFiles: [
          'src/pages/AnalysisRunner.jsx',
          'src/pages/ResultViewer.jsx',
          'src/components/analysis/',
          'src/logic/analysis/',
          'src/state/storage.js (extend only)',
        ],
        forbiddenFiles: ['src/logic/launcher/', 'src/logic/agents/'],
        requiredModules: ['analysisRunner', 'resultViewer'],
        requiredDataModels: ['JobResult', 'ProviderResponse'],
        requiredUiScreens: ['AnalysisRunnerPage', 'ResultViewerPage'],
        requiredStateTransitions: ['runAnalysisJob', 'saveResult'],
        requiredValidation: ['API key validated before call', 'Results sanitized before display'],
        stopConditions: ['Request hardcodes API keys', 'Request stores raw provider secrets'],
        rollbackGuidance: ['Remove runner pages', 'Restore Run 6 state'],
        acceptanceCriteria: ['Analysis can be run with user key', 'Results viewable', 'Build passes'],
      },
      {
        runNumber: 'Run 8',
        title: 'Report Builder + Analysis Export',
        mission: 'Add analysis report builder, comparison view, and safe export of analysis results.',
        dependsOn: ['Run 6', 'Run 7'],
        allowedFiles: [
          'src/pages/ReportBuilder.jsx',
          'src/components/analysis/',
          'src/logic/analysis/',
          'src/state/storage.js (extend only)',
        ],
        forbiddenFiles: ['src/logic/launcher/', 'src/logic/agents/'],
        requiredModules: ['reportBuilder'],
        requiredDataModels: ['Report', 'ComparisonRecord'],
        requiredUiScreens: ['ReportBuilderPage', 'AnalysisComparisonPage'],
        requiredStateTransitions: ['buildReport', 'exportAnalysisResult'],
        requiredValidation: ['Report export sanitized', 'No API keys in export'],
        stopConditions: ['Request exports raw API keys', 'Request calls external publish APIs'],
        rollbackGuidance: ['Remove report builder pages', 'Restore Run 7 state'],
        acceptanceCriteria: ['Reports buildable', 'Exports sanitized', 'Build passes'],
      },
    ],
  },

  employeeInductionPlatform: {
    productType: 'employeeInductionPlatform',
    productLabel: 'Employee Induction Platform',
    runs: [
      {
        runNumber: 'Run 6',
        title: 'Induction Data Model + Shell',
        mission: 'Create induction data model (inductees, programmes, steps, completions) and the dashboard shell.',
        dependsOn: ['Run 1', 'Run 2', 'Run 3', 'Run 4', 'Run 5'],
        allowedFiles: [
          'src/pages/InductionDashboard.jsx',
          'src/components/induction/',
          'src/logic/induction/',
          'src/state/storage.js (extend only)',
          'src/state/initialState.js (extend only)',
          'src/config/moduleRegistry.js',
        ],
        forbiddenFiles: ['src/logic/agents/', 'src/logic/transformer/', 'src/logic/launcher/'],
        requiredModules: ['inductionDashboard'],
        requiredDataModels: ['Inductee', 'InductionProgramme', 'InductionStep', 'Completion'],
        requiredUiScreens: ['InductionDashboardPage', 'ProgrammeList'],
        requiredStateTransitions: ['createInductee', 'startProgramme'],
        requiredValidation: ['Induction data uses SSOT', 'No HR system integration yet'],
        stopConditions: ['Request calls HR system APIs in this run', 'Request builds payroll logic'],
        rollbackGuidance: ['Remove induction state', 'Remove induction routes'],
        acceptanceCriteria: ['Induction dashboard renders', 'Inductees tracked', 'Build passes'],
      },
      {
        runNumber: 'Run 7',
        title: 'Step Builder + Policy Acknowledgements',
        mission: 'Build the induction step builder, policy document acknowledgement flow, and completion tracking.',
        dependsOn: ['Run 6'],
        allowedFiles: [
          'src/pages/StepBuilder.jsx',
          'src/pages/PolicyAcknowledgement.jsx',
          'src/components/induction/',
          'src/logic/induction/',
          'src/state/storage.js (extend only)',
        ],
        forbiddenFiles: ['src/logic/launcher/', 'src/logic/agents/'],
        requiredModules: ['stepBuilder', 'policyAcknowledgement'],
        requiredDataModels: ['InductionStep', 'PolicyDocument', 'AcknowledgementRecord'],
        requiredUiScreens: ['StepBuilderPage', 'PolicyAcknowledgementPage'],
        requiredStateTransitions: ['createStep', 'acknowledgePolicy', 'completeStep'],
        requiredValidation: ['Acknowledgements stored with timestamp', 'No PII stored without consent flow'],
        stopConditions: ['Request builds digital signature in this run without security review'],
        rollbackGuidance: ['Remove step builder pages', 'Restore Run 6 state'],
        acceptanceCriteria: ['Steps buildable', 'Policies acknowledgeable', 'Build passes'],
      },
      {
        runNumber: 'Run 8',
        title: 'Manager View + Certificate + Admin Export',
        mission: 'Add manager review dashboard, induction certificate generation, and admin data export.',
        dependsOn: ['Run 6', 'Run 7'],
        allowedFiles: [
          'src/pages/ManagerView.jsx',
          'src/pages/InductionCertificate.jsx',
          'src/components/induction/',
          'src/logic/induction/',
          'src/state/storage.js (extend only)',
        ],
        forbiddenFiles: ['src/logic/launcher/', 'src/logic/agents/'],
        requiredModules: ['managerView', 'inductionCertificate'],
        requiredDataModels: ['ManagerReview', 'InductionCertificate'],
        requiredUiScreens: ['ManagerViewPage', 'CertificatePage'],
        requiredStateTransitions: ['reviewInductee', 'issueCertificate', 'exportInductionData'],
        requiredValidation: ['Certificate generation local-only', 'Export sanitized'],
        stopConditions: ['Request exports inductee PII without consent flow', 'Request sends automated emails'],
        rollbackGuidance: ['Remove manager view pages', 'Restore Run 7 state'],
        acceptanceCriteria: ['Manager can review inductees', 'Certificates issued locally', 'Build passes'],
      },
    ],
  },

  supabaseHybridSaaS: {
    productType: 'supabaseHybridSaaS',
    productLabel: 'Supabase Hybrid SaaS',
    runs: [
      {
        runNumber: 'Run 6',
        title: 'Supabase Config + Auth Shell',
        mission: 'Create the Supabase client configuration layer and authentication shell. No live Supabase calls until keys are configured.',
        dependsOn: ['Run 1', 'Run 2', 'Run 3', 'Run 4', 'Run 5'],
        allowedFiles: [
          'src/config/supabaseConfig.js',
          'src/pages/AuthPage.jsx',
          'src/components/auth/',
          'src/logic/auth/',
          'src/state/storage.js (extend only)',
          'src/state/initialState.js (extend only)',
          'src/config/moduleRegistry.js',
        ],
        forbiddenFiles: [
          '.env (production secrets)',
          'src/logic/agents/',
          'src/logic/transformer/',
          'src/logic/launcher/',
        ],
        requiredModules: ['authPage'],
        requiredDataModels: ['AuthSession', 'UserProfile'],
        requiredUiScreens: ['AuthPage', 'ProfilePage'],
        requiredStateTransitions: ['loginUser', 'logoutUser', 'loadProfile'],
        requiredValidation: ['Supabase keys never hardcoded', 'Auth state uses SSOT'],
        stopConditions: ['Request hardcodes Supabase keys', 'Request builds payment engine in this run'],
        rollbackGuidance: ['Remove Supabase config', 'Remove auth pages', 'Remove auth state'],
        acceptanceCriteria: ['Auth shell renders', 'Login flow navigates', 'No hardcoded keys', 'Build passes'],
      },
      {
        runNumber: 'Run 7',
        title: 'Core SaaS Data Layer + CRUD',
        mission: 'Build the core SaaS data layer using Supabase tables, CRUD operations, and row-level security policies.',
        dependsOn: ['Run 6'],
        allowedFiles: [
          'src/logic/db/',
          'src/pages/DataDashboard.jsx',
          'src/components/saas/',
          'src/state/storage.js (extend only)',
        ],
        forbiddenFiles: ['src/logic/launcher/', 'src/logic/agents/', '.env (production secrets)'],
        requiredModules: ['dataDashboard'],
        requiredDataModels: ['SaaSRecord', 'TenantConfig'],
        requiredUiScreens: ['DataDashboardPage'],
        requiredStateTransitions: ['loadSaaSData', 'createRecord', 'updateRecord'],
        requiredValidation: ['RLS policies enforced', 'No raw SQL injection risk'],
        stopConditions: ['Request disables RLS', 'Request exposes service role key'],
        rollbackGuidance: ['Remove SaaS data layer', 'Restore Run 6 state'],
        acceptanceCriteria: ['CRUD works via Supabase', 'RLS enforced', 'Build passes'],
      },
      {
        runNumber: 'Run 8',
        title: 'Billing + Multi-Tenant + Admin Panel',
        mission: 'Add Stripe billing integration, multi-tenant config, and admin panel for SaaS management.',
        dependsOn: ['Run 6', 'Run 7'],
        allowedFiles: [
          'src/pages/BillingPage.jsx',
          'src/pages/TenantAdmin.jsx',
          'src/components/saas/',
          'src/logic/billing/',
          'src/state/storage.js (extend only)',
        ],
        forbiddenFiles: ['src/logic/launcher/', 'src/logic/agents/'],
        requiredModules: ['billingPage', 'tenantAdmin'],
        requiredDataModels: ['Subscription', 'Tenant', 'BillingRecord'],
        requiredUiScreens: ['BillingPage', 'TenantAdminPage'],
        requiredStateTransitions: ['subscribeToPlan', 'cancelSubscription', 'switchTenant'],
        requiredValidation: ['Stripe keys via environment only', 'No secret keys in frontend bundle'],
        stopConditions: ['Request embeds Stripe secret key in frontend', 'Request allows free access bypass'],
        rollbackGuidance: ['Remove billing pages', 'Remove Stripe config', 'Restore Run 7 state'],
        acceptanceCriteria: ['Billing UI renders', 'Subscriptions manageable', 'No secrets in bundle', 'Build passes'],
      },
    ],
  },

  localFirstPWAProduct: {
    productType: 'localFirstPWAProduct',
    productLabel: 'Local-First PWA Product',
    runs: [
      {
        runNumber: 'Run 6',
        title: 'PWA Core Data Model + Offline Shell',
        mission: 'Extend the PWA foundation with the core product data model and offline-first shell. Enhance service worker and manifest.',
        dependsOn: ['Run 1', 'Run 2', 'Run 3', 'Run 4', 'Run 5'],
        allowedFiles: [
          'src/pages/ProductHome.jsx',
          'src/components/pwa/',
          'src/logic/pwa/',
          'src/state/storage.js (extend only)',
          'src/state/initialState.js (extend only)',
          'src/config/moduleRegistry.js',
          'public/manifest.json',
          'public/sw.js',
        ],
        forbiddenFiles: ['src/logic/agents/', 'src/logic/transformer/', 'src/logic/launcher/'],
        requiredModules: ['productHome'],
        requiredDataModels: ['ProductRecord', 'UserPreference'],
        requiredUiScreens: ['ProductHomePage'],
        requiredStateTransitions: ['loadProductData', 'saveUserPreference'],
        requiredValidation: ['Offline-first behaviour confirmed', 'Service worker scoped correctly'],
        stopConditions: ['Request requires online-only API in this run', 'Request breaks existing PWA manifest'],
        rollbackGuidance: ['Remove product home pages', 'Remove PWA data model', 'Restore Run 5 manifest'],
        acceptanceCriteria: ['Product home renders offline', 'Data persists locally', 'Build passes'],
      },
      {
        runNumber: 'Run 7',
        title: 'Sync Engine + Background Sync',
        mission: 'Build the data sync engine with background sync support, conflict resolution, and sync status indicators.',
        dependsOn: ['Run 6'],
        allowedFiles: [
          'src/logic/pwa/syncEngine.js',
          'src/pages/SyncStatus.jsx',
          'src/components/pwa/',
          'src/state/storage.js (extend only)',
          'public/sw.js',
        ],
        forbiddenFiles: ['src/logic/launcher/', 'src/logic/agents/'],
        requiredModules: ['syncStatus'],
        requiredDataModels: ['SyncRecord', 'ConflictRecord'],
        requiredUiScreens: ['SyncStatusPage'],
        requiredStateTransitions: ['syncData', 'resolveConflict'],
        requiredValidation: ['Sync does not corrupt local data', 'Conflict resolution is user-triggered'],
        stopConditions: ['Request auto-resolves conflicts without user input', 'Request requires paid sync API'],
        rollbackGuidance: ['Remove sync engine', 'Remove service worker sync', 'Restore Run 6 state'],
        acceptanceCriteria: ['Sync status visible', 'Conflicts resolvable', 'Build passes'],
      },
      {
        runNumber: 'Run 8',
        title: 'Install Prompt + Push Notifications + Export',
        mission: 'Add PWA install prompt handling, push notification setup, and product data export.',
        dependsOn: ['Run 6', 'Run 7'],
        allowedFiles: [
          'src/logic/pwa/',
          'src/pages/InstallGuide.jsx',
          'src/components/pwa/',
          'src/state/storage.js (extend only)',
          'public/sw.js',
        ],
        forbiddenFiles: ['src/logic/launcher/', 'src/logic/agents/'],
        requiredModules: ['installGuide'],
        requiredDataModels: ['PushSubscription'],
        requiredUiScreens: ['InstallGuidePage'],
        requiredStateTransitions: ['handleInstallPrompt', 'subscribeToPush', 'exportProductData'],
        requiredValidation: ['Push notification permission is user-consented', 'Export sanitized'],
        stopConditions: ['Request sends push notifications without consent', 'Request exports private keys'],
        rollbackGuidance: ['Remove install guide pages', 'Remove push subscription state', 'Restore Run 7 state'],
        acceptanceCriteria: ['Install prompt handled', 'Push setup guided', 'Export works', 'Build passes'],
      },
    ],
  },

  customProductSystem: {
    productType: 'customProductSystem',
    productLabel: 'Custom Product System',
    runs: [
      {
        runNumber: 'Run 6',
        title: 'Custom Product Data Model + Shell',
        mission: 'Create the custom product data model and shell based on the validated transformation plan and blueprint.',
        dependsOn: ['Run 1', 'Run 2', 'Run 3', 'Run 4', 'Run 5'],
        allowedFiles: [
          'src/pages/CustomProductHome.jsx',
          'src/components/custom/',
          'src/logic/custom/',
          'src/state/storage.js (extend only)',
          'src/state/initialState.js (extend only)',
          'src/config/moduleRegistry.js',
        ],
        forbiddenFiles: ['src/logic/agents/', 'src/logic/transformer/', 'src/logic/launcher/'],
        requiredModules: ['customProductHome'],
        requiredDataModels: ['CustomRecord'],
        requiredUiScreens: ['CustomProductHomePage'],
        requiredStateTransitions: ['loadCustomData', 'saveCustomRecord'],
        requiredValidation: ['Custom data model matches blueprint', 'Uses SSOT'],
        stopConditions: ['Request overwrites transformation compiler state', 'Request builds second SSOT'],
        rollbackGuidance: ['Remove custom product pages', 'Remove custom state', 'Remove custom routes'],
        acceptanceCriteria: ['Custom shell renders', 'Data persists', 'Build passes'],
      },
      {
        runNumber: 'Run 7',
        title: 'Custom Feature Layer 1',
        mission: 'Build the first feature layer for the custom product as defined in the validated transformation plan.',
        dependsOn: ['Run 6'],
        allowedFiles: [
          'src/pages/CustomFeature1.jsx',
          'src/components/custom/',
          'src/logic/custom/',
          'src/state/storage.js (extend only)',
        ],
        forbiddenFiles: ['src/logic/launcher/', 'src/logic/agents/'],
        requiredModules: ['customFeature1'],
        requiredDataModels: [],
        requiredUiScreens: ['CustomFeature1Page'],
        requiredStateTransitions: [],
        requiredValidation: ['Features match transformation plan', 'No feature creep'],
        stopConditions: ['Request adds features not in transformation plan', 'Request overwrites Run 6 data model'],
        rollbackGuidance: ['Remove custom feature 1 pages', 'Restore Run 6 state'],
        acceptanceCriteria: ['Feature renders', 'Build passes'],
      },
      {
        runNumber: 'Run 8',
        title: 'Custom Feature Layer 2 + Export',
        mission: 'Build the second feature layer and add product export capability.',
        dependsOn: ['Run 6', 'Run 7'],
        allowedFiles: [
          'src/pages/CustomFeature2.jsx',
          'src/components/custom/',
          'src/logic/custom/',
          'src/state/storage.js (extend only)',
        ],
        forbiddenFiles: ['src/logic/launcher/', 'src/logic/agents/'],
        requiredModules: ['customFeature2'],
        requiredDataModels: [],
        requiredUiScreens: ['CustomFeature2Page'],
        requiredStateTransitions: [],
        requiredValidation: ['No duplicate state', 'Export sanitized'],
        stopConditions: ['Request adds features not in transformation plan'],
        rollbackGuidance: ['Remove custom feature 2 pages', 'Restore Run 7 state'],
        acceptanceCriteria: ['Feature 2 renders', 'Export works', 'Build passes'],
      },
    ],
  },
};

export function getRunSequenceForProduct(productType) {
  return PRODUCT_RUN_SEQUENCES[productType] || null;
}

export function getRunForProduct(productType, runNumber) {
  const seq = getRunSequenceForProduct(productType);
  if (!seq) return null;
  return seq.runs.find((r) => r.runNumber === runNumber) || null;
}

export function getAllProductTypes() {
  return Object.keys(PRODUCT_RUN_SEQUENCES);
}

export default PRODUCT_RUN_SEQUENCES;
